# Generated by Django 4.1.7 on 2023-02-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselistingmodel',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
